#!/bin/bash

is_gnome() (
    # XDG_CURRENT_DESKTOP is a colon-separated list of desktop environments
    IFS=':'
    for DE in ${XDG_CURRENT_DESKTOP,,}; do
        if [[ "gnome" == "$DE" ]]; then return; fi
    done
    return 1
)

# For dark mode support on GNOME
if is_gnome; then
    export QT_QPA_PLATFORMTHEME=gnome
fi

export LD_LIBRARY_PATH="$SNAP/kf6/usr/lib/$SNAP_LAUNCHER_ARCH_TRIPLET:$SNAP/kf6/usr/lib:$SNAP/kf6/usr/lib/$SNAP_LAUNCHER_ARCH_TRIPLET/libproxy:$SNAP/kf6/lib/$SNAP_LAUNCHER_ARCH_TRIPLET:$SNAP/usr/lib/$SNAP_LAUNCHER_ARCH_TRIPLET:$LD_LIBRARY_PATH"
export PYTHONPATH="$SNAP/usr/lib/python3/dist-packages"

exec "$@"
